name: CI Backend Karsa Jobs

on:
  push:
    branches:
      - karsajobs

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile

  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run Unit Test
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    needs: [lint-dockerfile, test-app]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u zallengrad --password-stdin
      - name: Build and Push Image
        run: |
          IMAGE_NAME="ghcr.io/zallengrad/karsajobs:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
